#!/bin/sh
# Copyright 2012 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# git gofmt & go mod tidy pre-commit hook
#
# To use, store as .git/hooks/pre-commit inside your repository and make sure
# it has execute permissions.
#
# This script does not handle file names that contain spaces.

failWithMessage() {
	echo >&2 $1
	exit 1
}

# Adapted from dnephin/pre-commit-golang
go mod tidy -v 2>&1 | grep -q "updates to go.mod needed" && failWithMessage "go mod tidy: updates to go.mod needed"
git diff --exit-code go.* &> /dev/null || failWithMessage "go.mod or go.sum differs, please re-add it to your commit"

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
[ -z "$gofiles" ] && exit 0

unformatted=$(gofmt -l $gofiles)
[ -z "$unformatted" ] && exit 0

# Some files are not gofmt'd. Print message and fail.
msg="Go files must be formatted with gofmt. Please run:"
for fn in $unformatted; do
	msg+="\n  gofmt -w $PWD/$fn"
done
failWithMessage msg
