name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install dependencies
        run: go get .

      - name: Formatting
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then gofmt -s -l .;  exit 1; fi

      - name: Run tests
        run: make test